# see ./configure for interactive use.
# why pass arguments to make is bad
# https://stackoverflow.com/questions/2214575/passing-arguments-to-make-run/45003119#45003119
# https://stackoverflow.com/questions/6273608/how-to-pass-argument-to-makefile-from-command-line
run:
	export FLASK_ENV=development && flask run
